### ISSUE TITLE
React 18 doesn't support it

### ISSUE THREAD

**Issue by codelikepro22** [specter256/react-simple-image-viewer#20]
We couldn't install it in React 18

**Comment by specter256** [comment]
I just updated a [demo](https://codesandbox.io/s/react-simple-image-viewer-demo-4itlr) that uses React 18 and everything seems to be working fine. Can you provide any error messages?

**Comment by codelikepro22** [comment]
**npm i simple-react-lightbox**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from simple-react-lightbox@3.6.9-0
npm ERR! node_modules/simple-react-lightbox
npm ERR!   simple-react-lightbox@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.




**npm i react-simple-image-viewer**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from react-simple-image-viewer@1.2.1
npm ERR! node_modules/react-simple-image-viewer
npm ERR!   react-simple-image-viewer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by specter256** [comment]
Just released version 1.2.2, can you please try it?

**Comment by codelikepro22** [comment]
It is now working. Thanks.
