### ISSUE TITLE
[NextJs] Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by leadream** [specter256/react-simple-image-viewer#3]
Hi, thanks for your great work of this library. I'm trying to use it in my NextJs app but it throws an error. Seems like NextJs doesn't support importing CSS from node_modules so could you separate style from the `index.js`?  Thanks in advance.

BTW, the full error information is [here](https://github.com/vercel/next.js/blob/master/errors/css-npm.md).

**Comment by specter256** [comment]
I moved the style definitions from the css file to `styled-components`. You can still override styles using class names. Please update the package to version 0.0.7 and check if that fixed your issue.

**Comment by leadream** [comment]
@specter256 Thanks, will try it.
