### ISSUE TITLE
Is it possible to render it inside of parent container?

### ISSUE THREAD

**Issue by ongmk** [specter256/react-simple-image-viewer#5]
I see that this component is rendered at a completely different location outside of my react app. As the title suggested, I just wanna know if there is a way to render this inside a parent container instead?

**Comment by specter256** [comment]
Unfortunately, this is not possible at the moment. Maybe in future versions this will be implemented. Anyway, pull-requests are welcome.

**Comment by ongmk** [comment]
I see. Thanks for your reply!
