### ISSUE TITLE
Can we have a prop to enable/disable Scroll to change images

### ISSUE THREAD

**Issue by jontycool** [specter256/react-simple-image-viewer#8]
Hi, 
Thanks for your efforts in creating this. But in my current implementation, when I open the image-viewer and start scrolling to change images, the main webpage behind also gets scrolled up/down. So can we have a prop which enables/disables the scroll to change image functionality.

**Comment by specter256** [comment]
Hi! A new property `disableScroll` was added in version 1.0.0, please try it.
